export const LoginUser = async ({ login, pas }) => {
	try {
		console.log(login, pas)
	} catch (error) {
		console.log(error)
	}
}
